### ISSUE TITLE
update to version 1.1.0: error on start

### ISSUE THREAD

**Issue by cflurin** [pierrecle/node-red-contrib-mi-devices#14]
Hi,
I've updated to version 1.1.0 and I get this error:
```sh
11 Jan 11:26:13 - [error] [xiaomi-gateway in:9ff24178.d0cb7] node-red-contrib-mi-devices:udp.errors.error
```

The previous version was ok.

**Comment by bemble** [comment]
Thanks for the feed-back, I'll take a look.
In fact I want to refactor these nodes (gateway in/out).

**Comment by cflurin** [comment]
Hi,
I'd like to use your node. When may we expect a new version?

**Comment by bemble** [comment]
Hi,
I think by the end of the next week. I took me more time to try `miio` so everything as been delayed, sorry.

**Comment by cflurin** [comment]
I've developed an own app (mqtt-server).
