### ISSUE TITLE
Move to miio

### ISSUE THREAD

**Issue by bemble** [pierrecle/node-red-contrib-mi-devices#31]
Finally, `lumi-aqara` doesn't handle multiple gateways. Moving to `miio` seams to be the best solution.
But for now, `miio` does not support gateway sound and Aqara door sensor.

Need to PR `miio` for this to be iso with what the plugin provide before.

2 issues before beeing able to switch:
- aholstenson/miio#101
- aholstenson/miio#69

**Comment by readeral** [comment]
Hey Pierrecle, thanks so much for all your work on this node-red plugin. I'm yet to get it all working in my setup, but suspect I should wait until 2.0.0 is released to invest time heavily...

I'm curious whether the move to miio will enable the use of other non-gateway devices relatively easily? (Particularly, Robot Vac in my case, but that's inconsequential)

**Comment by bemble** [comment]
Hey, thanks.
You're right, you should wait for 2.0.0, cause every node will be renamed...

The use of miio bring also this advantage, support easilly more devices, even not connected to a gateway, like the Robot Vac yes. But, there's one "but", in mi-devices, I test everything to prevent any "supposed to work". That means that I have to purchase every device that I want to support. And for now, I don't own Robot Vac, so, I think you'll have to implemet the node yourself and I'll be pleased to accept a PR, until I'll get such device ;)

You'll see in the v2.0.0 that I try to let the code be as simple as possible to let people add features easilly.

**Comment by bemble** [comment]
This take too much time, `miio` is harder to integrate than expected (devices not recognised here, difficult to move ahead, no event for some devices). Plus, playing sounds is not yet possible with `miio`.
I will probably release a v2.0.0 without `miio`, but keep some parts of what I’ve done (like search for gateways and sub devices).

**Comment by readeral** [comment]
This is a shame, it seems like miio is the most robust implementation available at the moment, and would be good to benefit from both @aholstenson and your own cumulative efforts.

**Comment by bemble** [comment]
@readeral Please choose your words and remember that behind those pieces of software, there is people, like me, who spend their time writing this code instead of, for example, spend this time with their families.
Feel free to contribute either to `node-red-contrib-mi-devices` and `miio` to fit both needs and behavior.
`miio` is not that robust and finished, take a look at the opened issues, and neither, for me, easy to contribute.
Now that's said, I'll not use `miio` for the gateway, see upper, but that does not mean that I'll not use it for other stuff, if it fit well with both devices and `nodered`.

**Comment by readeral** [comment]
Hi Pierre, my apologies if I caused offence, I was trying to be encouraging! I guess maybe a cultural difference in expression from an Australian to a Frenchman. What I meant was 'how disappointing the integration isn't viable'. I'm sorry. In any case, please don't think I'm trying to freeload. I have already asked last week how I can contribute to documentation, have submitted two pull requests this week, and am working on patching support for the aqara human body sensor (as well as eventually that Robot Vac content) I hope that it's obvious I intend to support your work, not to bring you down! I also understand the family pressure, I have a 6 week old son, so am limited in what I can do, but if you have particular things you'd like to open up for the community to contribute towards, I'll do my best.

**Comment by bemble** [comment]
No problem, it was the "this is a shame" that offenses me, but I understand your point and what you meant. I fully agree with you but things are not going as I expected with `miio`.

My point is that integrating `miio` for the gateway and its subdevices will take me too much effort (in bug fixing - like why magnets are not recognized as `closed` at startup - and add some behaviors - like playing sounds on the gateway - to `miio`, find how I could interface it with `nodered` to be the most smooth for my uses etc.) where I could just clean up my code to fit my needs (which is what I'll do). I also try to do my best to provide something the most easy to contribute to. I hope you'll enjoy v2, and, if I don't because I don't own one, you'll be able to handle the vacuum easily.

I noticed and appreciated your contributions, but for now I block them until I release the v2 (which should come very soon, but my 18 month son require some time as you could imagine 😉).
